import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { hostname } from "node:os";
import path from "node:path";
import { eq } from "drizzle-orm";
import { getDb } from "@/db/client";
import { employees } from "@/db/schema";
import { getSettings } from "@/server/domain/settings";
import { slugify } from "./summary";

/**
 * One-click Home Assistant integration install. Writes into the HA config
 * share (map: homeassistant_config):
 *
 *   packages/timeclock.yaml   rest_command + one toggle script per employee
 *                             (companion-app widgets call these)
 *   www/timeclock-card.js     the custom dashboard card
 *
 * Both are regenerated automatically (boot, employee changes, key rotation)
 * once installed, so scripts track the roster and card updates ship with the
 * add-on. Requires `packages: !include_dir_named packages` in the user's
 * configuration.yaml — surfaced by status() so the UI can walk them through.
 */

const HA_CONFIG = process.env.HA_CONFIG_DIR || "/homeassistant";
const CARD_SOURCE =
  process.env.CARD_SOURCE || path.join(process.cwd(), "public", "timeclock-card.js");
const PORT = process.env.INGRESS_PORT || "8099";

const packagePath = () => path.join(HA_CONFIG, "packages", "timeclock.yaml");
const cardPath = () => path.join(HA_CONFIG, "www", "timeclock-card.js");

/** YAML double-quoted scalar (JSON strings are valid YAML). */
const q = (s: string) => JSON.stringify(s);

export function addonBaseUrl(): string {
  // The container hostname is the add-on's DNS name on the internal docker
  // network — resolvable from HA Core. (env HOSTNAME is unreliable here: the
  // run script overwrites it with the bind address.)
  return `http://${hostname()}:${PORT}`;
}

export async function buildPackageYaml(): Promise<string> {
  const { integration } = await getSettings();
  const staff = await getDb().select().from(employees).where(eq(employees.active, true));
  const base = addonBaseUrl();

  const scripts = staff
    .map((e) => {
      const slug = slugify(e.displayName);
      return `  timeclock_${slug}_toggle:
    alias: ${q(`Time Clock: ${e.displayName} in/out`)}
    icon: mdi:clock-check
    mode: single
    sequence:
      - service: rest_command.timeclock_punch
        data:
          employee: ${q(e.id)}
          action: toggle`;
    })
    .join("\n");

  return `# Generated by the Time Clock add-on — DO NOT EDIT.
# Regenerated automatically when employees change (Admin -> Settings -> Integration).
rest_command:
  timeclock_punch:
    url: ${q(`${base}/api/ext/punch`)}
    method: post
    headers:
      x-timeclock-key: ${q(integration.apiKey)}
    content_type: "application/json"
    payload: >-
      {"employee": "{{ employee }}", "action": "{{ action | default('toggle') }}"}

script:
${scripts || "  {}"}
`;
}

export interface IntegrationStatus {
  haConfigMounted: boolean;
  packageInstalled: boolean;
  cardInstalled: boolean;
  packagesIncludeConfigured: boolean | null; // null = couldn't read configuration.yaml
  addonUrl: string;
}

export async function integrationStatus(): Promise<IntegrationStatus> {
  let packagesInclude: boolean | null = null;
  try {
    const cfg = readFileSync(path.join(HA_CONFIG, "configuration.yaml"), "utf8");
    packagesInclude = /^\s*packages\s*:/m.test(cfg);
  } catch {
    packagesInclude = null;
  }
  return {
    haConfigMounted: existsSync(HA_CONFIG),
    packageInstalled: existsSync(packagePath()),
    cardInstalled: existsSync(cardPath()),
    packagesIncludeConfigured: packagesInclude,
    addonUrl: addonBaseUrl(),
  };
}

export async function installIntegration(): Promise<IntegrationStatus> {
  if (!existsSync(HA_CONFIG)) {
    throw new Error(`HA config not mounted at ${HA_CONFIG} (map: homeassistant_config missing?)`);
  }
  mkdirSync(path.join(HA_CONFIG, "packages"), { recursive: true });
  mkdirSync(path.join(HA_CONFIG, "www"), { recursive: true });
  writeFileSync(packagePath(), await buildPackageYaml(), "utf8");
  writeFileSync(cardPath(), readFileSync(CARD_SOURCE));
  await reloadHaYaml();
  return integrationStatus();
}

/** Once installed, keep generated files current without admin action. */
export async function refreshIntegrationIfInstalled(): Promise<void> {
  if (!existsSync(packagePath())) return;
  try {
    writeFileSync(packagePath(), await buildPackageYaml(), "utf8");
    if (existsSync(CARD_SOURCE)) writeFileSync(cardPath(), readFileSync(CARD_SOURCE));
    await reloadHaYaml();
  } catch (e) {
    console.error("[ha-install] refresh failed:", e instanceof Error ? e.message : e);
  }
}

/** Ask HA to re-read YAML (picks up rest_command/script changes, no restart). */
async function reloadHaYaml(): Promise<void> {
  const token = process.env.SUPERVISOR_TOKEN;
  if (!token) return;
  const res = await fetchImpl("http://supervisor/core/api/services/homeassistant/reload_all", {
    method: "POST",
    headers: { authorization: `Bearer ${token}`, "content-type": "application/json" },
    body: "{}",
  });
  if (!res.ok) console.error(`[ha-install] reload_all: ${res.status}`);
}

// Injectable for tests.
export let fetchImpl: typeof fetch = fetch;
export function setFetchImpl(f: typeof fetch) {
  fetchImpl = f;
}
