import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { hostname } from "node:os";
import path from "node:path";
import { eq } from "drizzle-orm";
import { getDb } from "@/db/client";
import { employees } from "@/db/schema";
import { getSettings } from "@/server/domain/settings";
import { slugify } from "./summary";

/**
 * One-click Home Assistant integration install. Writes into the HA config
 * share (map: homeassistant_config), split into two package files so reloads
 * stay narrow:
 *
 *   packages/timeclock.yaml            `script:` — one toggle per employee
 *                                     (companion widgets). Changes on every
 *                                     roster edit -> `script.reload` only.
 *   packages/timeclock_handlers.yaml   `rest_command:` only. Carries the API
 *                                     key + add-on URL, so it changes on key
 *                                     rotation / add-on move -> `rest_command`
 *                                     reload then, and ONLY then.
 *   packages/timeclock_automation.yaml the single notification-action
 *                                     `automation:`. FULLY static content, so
 *                                     `automation.reload` fires only when this
 *                                     file's bytes actually change (i.e. an
 *                                     add-on upgrade that revises the handler),
 *                                     never on roster edits, key rotation, or a
 *                                     no-change boot.
 *   www/timeclock-card.js              the custom dashboard card.
 *
 * Never `homeassistant.reload_all` — this box runs a whole grow facility from
 * packages/, and a global reload restarts every automation mid-run.
 * Requires `packages: !include_dir_named packages` in configuration.yaml —
 * surfaced by status() so the UI can walk the admin through it.
 */

const HA_CONFIG = process.env.HA_CONFIG_DIR || "/homeassistant";
const CARD_SOURCE =
  process.env.CARD_SOURCE || path.join(process.cwd(), "public", "timeclock-card.js");
const PORT = process.env.INGRESS_PORT || "8099";

const scriptsPath = () => path.join(HA_CONFIG, "packages", "timeclock.yaml");
const handlersPath = () => path.join(HA_CONFIG, "packages", "timeclock_handlers.yaml");
const automationPath = () => path.join(HA_CONFIG, "packages", "timeclock_automation.yaml");
const cardPath = () => path.join(HA_CONFIG, "www", "timeclock-card.js");

/** YAML double-quoted scalar (JSON strings are valid YAML). */
const q = (s: string) => JSON.stringify(s);

export function addonBaseUrl(): string {
  // The container hostname is the add-on's DNS name on the internal docker
  // network — resolvable from HA Core. (env HOSTNAME is unreliable here: the
  // run script overwrites it with the bind address.)
  return `http://${hostname()}:${PORT}`;
}

/** `script:` doc — one toggle per active employee. Changes with the roster. */
export async function buildScriptsYaml(): Promise<string> {
  // Order deterministically by id so DB row-order jitter can't produce a
  // byte-different file (which would trigger a spurious script.reload on boot).
  const staff = await getDb()
    .select()
    .from(employees)
    .where(eq(employees.active, true))
    .orderBy(employees.id);

  // Two display names can slugify to the same key (e.g. "José"/"Jose", or two
  // "John Smith"s). Duplicate YAML mapping keys break HA package loading on the
  // facility box, so keep only the first per slug and suffix later collisions.
  const seen = new Map<string, number>();
  const scripts = staff
    .map((e) => {
      const base = slugify(e.displayName);
      const n = seen.get(base) ?? 0;
      seen.set(base, n + 1);
      const slug = n === 0 ? base : `${base}_${n + 1}`;
      return `  timeclock_${slug}_toggle:
    alias: ${q(`Time Clock: ${e.displayName} in/out`)}
    icon: mdi:clock-check
    mode: single
    sequence:
      - service: rest_command.timeclock_punch
        data:
          employee: ${q(e.id)}
          action: toggle`;
    })
    .join("\n");

  return `# Generated by the Time Clock add-on — DO NOT EDIT.
# Per-employee clock in/out scripts (companion-app widgets). Regenerated when
# the roster changes; triggers only a script.reload.
script:
${scripts || "  {}"}
`;
}

/**
 * `rest_command:` doc — carries the API key + add-on URL. This is the only
 * dynamic handler content, so it (and the `rest_command.reload` it triggers)
 * changes on key rotation or add-on move — never on routine roster edits, and
 * never touches the notification automation.
 */
export async function buildHandlersYaml(): Promise<string> {
  const { integration } = await getSettings();
  const base = addonBaseUrl();
  return `# Generated by the Time Clock add-on — DO NOT EDIT.
# rest_command only. Carries the API key + add-on URL, so this reloads only on
# key rotation / add-on move — it never triggers an automation reload.
rest_command:
  timeclock_punch:
    url: ${q(`${base}/api/ext/punch`)}
    method: post
    headers:
      x-timeclock-key: ${q(integration.apiKey)}
    content_type: "application/json"
    payload: >-
      {"employee": "{{ employee }}", "action": "{{ action | default('toggle') }}"}
`;
}

/**
 * The single notification-action `automation:` doc. FULLY static — no interpolated
 * values — so its bytes only change on an add-on upgrade that revises the handler
 * itself. That means `automation.reload` (which re-reads every automation on the
 * facility box) fires essentially never after first install: not on roster edits,
 * not on key rotation, not on a no-change boot. The automation turns a
 * "Clock in"/"Clock out" notification button tap (action id
 * "TIMECLOCK_IN__<id>" / "TIMECLOCK_OUT__<id>") into a punch.
 */
export function buildAutomationYaml(): string {
  return `# Generated by the Time Clock add-on — DO NOT EDIT.
# Static notification-action handler. Kept in its own file so it never reloads
# on roster/key changes — only if the add-on ships a new version of it.
automation:
  - id: timeclock_notify_actions
    alias: "Time Clock: clock in/out from notification buttons"
    mode: parallel
    max: 20
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
    condition:
      - condition: template
        value_template: >-
          {{ trigger.event.data.action is defined
             and trigger.event.data.action.startswith('TIMECLOCK_') }}
    action:
      - variables:
          _parts: "{{ trigger.event.data.action.split('__') }}"
      - service: rest_command.timeclock_punch
        data:
          employee: "{{ _parts[1] }}"
          action: "{{ 'in' if _parts[0] == 'TIMECLOCK_IN' else 'out' }}"
`;
}

/** Strip a generated file's leading comment banner (for concatenation). */
const stripBanner = (s: string) => s.replace(/^#[^\n]*\n(#[^\n]*\n)*/, "");

/** Combined single-file view for the manual-install / copy-paste path. */
export async function buildPackageYaml(): Promise<string> {
  const handlers = await buildHandlersYaml();
  const automation = buildAutomationYaml();
  const scripts = await buildScriptsYaml();
  // Concatenate the three docs, stripping the trailing files' comment banners.
  return `${handlers}\n${stripBanner(automation)}\n${stripBanner(scripts)}`;
}

export interface IntegrationStatus {
  haConfigMounted: boolean;
  packageInstalled: boolean;
  cardInstalled: boolean;
  packagesIncludeConfigured: boolean | null; // null = couldn't read configuration.yaml
  addonUrl: string;
}

export async function integrationStatus(): Promise<IntegrationStatus> {
  let packagesInclude: boolean | null = null;
  try {
    const cfg = readFileSync(path.join(HA_CONFIG, "configuration.yaml"), "utf8");
    packagesInclude = /^\s*packages\s*:/m.test(cfg);
  } catch {
    packagesInclude = null;
  }
  return {
    haConfigMounted: existsSync(HA_CONFIG),
    packageInstalled:
      existsSync(scriptsPath()) && existsSync(handlersPath()) && existsSync(automationPath()),
    cardInstalled: existsSync(cardPath()),
    packagesIncludeConfigured: packagesInclude,
    addonUrl: addonBaseUrl(),
  };
}

/** Write a file only when content differs; returns true when it wrote. */
function writeIfChanged(file: string, content: string | Buffer): boolean {
  try {
    const current = readFileSync(file);
    if (current.equals(Buffer.isBuffer(content) ? content : Buffer.from(content))) return false;
  } catch {
    // missing -> write
  }
  writeFileSync(file, content);
  return true;
}

/** Write all package files + card; reload only the domains whose file changed. */
async function writeAndReload(): Promise<void> {
  mkdirSync(path.join(HA_CONFIG, "packages"), { recursive: true });
  mkdirSync(path.join(HA_CONFIG, "www"), { recursive: true });
  const scriptsChanged = writeIfChanged(scriptsPath(), await buildScriptsYaml());
  const handlersChanged = writeIfChanged(handlersPath(), await buildHandlersYaml());
  const automationChanged = writeIfChanged(automationPath(), buildAutomationYaml());
  if (existsSync(CARD_SOURCE)) writeIfChanged(cardPath(), readFileSync(CARD_SOURCE));

  const reloads: string[] = [];
  if (scriptsChanged) reloads.push("script/reload");
  // rest_command carries the (dynamic) key/URL; reload it only when that file
  // changed. It is INDEPENDENT of the automation reload.
  if (handlersChanged) reloads.push("rest_command/reload");
  // automation.reload re-reads every automation on the facility box, so it is
  // gated on the fully-static automation file's bytes changing — which happens
  // only when the add-on ships a revised handler, never on roster/key edits or
  // a no-change boot.
  if (automationChanged) reloads.push("automation/reload");
  await reload(reloads);
}

export async function installIntegration(): Promise<IntegrationStatus> {
  if (!existsSync(HA_CONFIG)) {
    throw new Error(`HA config not mounted at ${HA_CONFIG} (map: homeassistant_config missing?)`);
  }
  await writeAndReload();
  return integrationStatus();
}

/** Once installed, keep generated files current without admin action. */
export async function refreshIntegrationIfInstalled(): Promise<void> {
  // Only refresh if the integration was previously installed (any generated
  // file present). If everything is byte-identical this is a full no-op — no
  // reload is issued (see writeAndReload + the empty-list guard in reload()).
  if (!existsSync(scriptsPath()) && !existsSync(handlersPath()) && !existsSync(automationPath())) {
    return;
  }
  try {
    await writeAndReload();
  } catch (e) {
    console.error("[ha-install] refresh failed:", e instanceof Error ? e.message : e);
  }
}

/**
 * Reload only the given domains. NEVER homeassistant.reload_all: this HA runs a
 * whole facility out of packages and a global reload restarts every automation
 * on the box mid-run. `automation.reload` is only ever passed here when the
 * fully-static automation file changed (an add-on upgrade that revises the
 * handler) — never on roster edits, key rotation, or a no-change boot. An empty
 * list is a hard no-op (no HTTP call at all).
 */
async function reload(services: string[]): Promise<void> {
  const token = process.env.SUPERVISOR_TOKEN;
  if (!token || services.length === 0) return;
  for (const svc of services) {
    const res = await fetchImpl(`http://supervisor/core/api/services/${svc}`, {
      method: "POST",
      headers: { authorization: `Bearer ${token}`, "content-type": "application/json" },
      body: "{}",
    });
    if (!res.ok) console.error(`[ha-install] ${svc}: ${res.status}`);
  }
}

// Injectable for tests.
export let fetchImpl: typeof fetch = fetch;
export function setFetchImpl(f: typeof fetch) {
  fetchImpl = f;
}
